version: '3'

services:
  backend:
    build: ./docker-config/backend
    environment:
      - PGUSER=hypertube
      - PGHOST=postgres
      - PGPASSWORD=Hypertube12345
      - PGDATABASE=hypertubedb
      - PGPORT=5432
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
  frontend:
    build: ./docker-config/frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
  proxy:
    build: ./docker-config/proxy
    ports:
      - '8080:8080'
    links:
      - frontend:frontend
      - backend:backend
  postgres:
    build: ./docker-config/postgres
    environment:
      - POSTGRES_USER=hypertube
      - POSTGRES_PASSWORD=Hypertube12345
      - POSTGRES_DB=hypertubedb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
