version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
  proxy:
    build: ./proxy
    ports:
      - '8080:8080'
    links:
      - frontend:frontend
      - backend:backend
  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=hypertube
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hypertubedb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
